language: python
python:
  - "2.7"

dist: trusty

services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

cache: pip

install:
  - pip install -r requirements.txt

script: python -m unittest discover -p "logic_tests.py"
